"""initial 6

Revision ID: 0f7d21d7da70
Revises: 773e35dc3df1
Create Date: 2023-07-17 22:22:50.300626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7d21d7da70'
down_revision = '773e35dc3df1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
