"""initial 6

Revision ID: 426d03c0b698
Revises: 7cd6812b4031
Create Date: 2023-07-17 21:31:09.951381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426d03c0b698'
down_revision = '7cd6812b4031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'user_id')
    # ### end Alembic commands ###
