"""initial4

Revision ID: 5ccd5062b53d
Revises: 21d022905550
Create Date: 2023-07-16 22:36:47.811291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccd5062b53d'
down_revision = '21d022905550'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    # ### end Alembic commands ###
