"""initial 6

Revision ID: 70e759a7703d
Revises: e1c4c44e13d9
Create Date: 2023-07-17 21:06:19.015049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e759a7703d'
down_revision = 'e1c4c44e13d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
