"""initial 6

Revision ID: 773e35dc3df1
Revises: 426d03c0b698
Create Date: 2023-07-17 21:37:19.953656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773e35dc3df1'
down_revision = '426d03c0b698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_user_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'user_id')
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.add_column('role', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('role_user_id_fkey', 'role', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
