"""initial 6

Revision ID: 7cd6812b4031
Revises: 98b4194d31bc
Create Date: 2023-07-17 21:20:40.303567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd6812b4031'
down_revision = '98b4194d31bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
