"""initial 6

Revision ID: 98b4194d31bc
Revises: 70e759a7703d
Create Date: 2023-07-17 21:13:59.749913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b4194d31bc'
down_revision = '70e759a7703d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
