"""initial 5

Revision ID: d661c32b77fb
Revises: dae82cc3030d
Create Date: 2023-07-17 20:59:24.416438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd661c32b77fb'
down_revision = 'dae82cc3030d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'user_id')
    # ### end Alembic commands ###
